### ISSUE TITLE
Don't require peer of `electron@*`

### ISSUE THREAD

**Issue by leo** [tommoor/electron-lets-move#3]
Most electron apps are using two packages like you can see [here](https://github.com/zeit/now-desktop) and [here](https://github.com/zeit/now-desktop/tree/master/app). In turn, the "electron" package won't be inside the `package.json` where your package sits.

This will make npm keep throwing the error!

> npm WARN electron-lets-move@0.0.4 requires a peer of electron@* but none was installed.

**Comment by tommoor** [comment]
Thanks for the note, I've fixed in 55cff788ab181772881fe87d64bfa1ee0e7ff0cd and `v0.0.5`
